name: builds

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1.10.0
    
    - name: Setup vcpkg & dependencies
      uses: lukka/run-vcpkg@v11.0
      with:
        vcpkgGitCommitId: 74e6536215718009aae747d86d84b78376bf9e09
        runVcpkgInstall: true
        doNotCache: false
    
    - name: Build
      uses: lukka/run-cmake@v10.0
      with:
        configurePreset: build-release-msvc
        buildPreset: release-msvc
        configurePresetAdditionalArgs: "['-DOUTPUT_FOLDER=dist']"
    
    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: build_result
        path: dist
        if-no-files-found: error
        overwrite: true
